[tool.poetry]
name = "AI_SP500"
version = "0.0.0"
description = "Data Architecture to manually support a data mining solution to daily analyse the SP500 stock market index."
authors = ["Tiago Reis <you@example.com>"]
readme = "README.md"
package-mode = false
license = "GPL-3.0-only"
homepage = "https://github.com/Tiago-B-C-Reis/AI_SP500"
repository = "https://github.com/Tiago-B-C-Reis/AI_SP500"
documentation = "https://github.com/Tiago-B-C-Reis/AI_SP500#readme"
keywords = ["sp500", "data-pipeline", "finance", "alpha-vantage", "s3"]

[tool.poetry.dependencies]
python = "^3.9"
pyspark = "^3.5.1"
python-dotenv = "^1.2.1"
boto3 = "1.35.24"
requests = "^2.32.2"
pandas = "^2.0.2"
beautifulsoup4 = "^4.12.3"
# Yahoo Finance (yfinance API)
yfinance = "^0.2.43"
# Yahoo Finance (Yahoo_fin API)
yahoo-fin = "^0.8.9.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# pip install poetry
# poetry install
